# Generated by Django 4.1.7 on 2023-04-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bloodbank',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
